version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

includes:
  dotnet:
    taskfile: ./Taskfile.DOTNET.yml
    dir: .
  build:
    taskfile: ./Taskfile.DOCKER.yml
    dir: .
